-- MySQL Script generated by MySQL Workbench
-- Mon May  8 17:54:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema student_success_journal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `student_success_journal` ;

-- -----------------------------------------------------
-- Schema student_success_journal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `student_success_journal` DEFAULT CHARACTER SET utf8 ;
USE `student_success_journal` ;

-- -----------------------------------------------------
-- Table `student_success_journal`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`courses` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`groups` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_courses1_idx` (`courses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`users` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`students` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` INT NULL,
  `groups_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_groups1_idx` (`groups_id` ASC) VISIBLE,
  INDEX `fk_students_courses1_idx` (`courses_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`disciplines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`disciplines` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number_of_hours` INT NOT NULL,
  `lecturer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`marks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`marks` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`marks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `grades` INT NOT NULL,
  `students_id` INT NOT NULL,
  `disciplines_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marks_students1_idx` (`students_id` ASC) VISIBLE,
  INDEX `fk_marks_disciplines1_idx` (`disciplines_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`lesson_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`lesson_type` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`lesson_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`disciplines_has_lesson_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`disciplines_has_lesson_type` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`disciplines_has_lesson_type` (
  `lesson_type_id` INT NOT NULL,
  `disciplines_id` INT NOT NULL,
  PRIMARY KEY (`lesson_type_id`, `disciplines_id`),
  INDEX `fk_lesson_type_has_disciplines_disciplines1_idx` (`disciplines_id` ASC) VISIBLE,
  INDEX `fk_lesson_type_has_disciplines_lesson_type_idx` (`lesson_type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`absences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`absences` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`absences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `cause` VARCHAR(45) NULL,
  `students_id` INT NOT NULL,
  `disciplines_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_absences_students1_idx` (`students_id` ASC) VISIBLE,
  INDEX `fk_absences_disciplines1_idx` (`disciplines_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`roles` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`roles_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`roles_has_users` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`roles_has_users` (
  `roles_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `users_id`),
  INDEX `fk_roles_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_roles_has_users_roles1_idx` (`roles_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student_success_journal`.`total`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_success_journal`.`total` ;

CREATE TABLE IF NOT EXISTS `student_success_journal`.`total` (
  `id` INT NOT NULL,
  `month` VARCHAR(45) NOT NULL,
  `gpa` DOUBLE NOT NULL,
  `quantity_of_absences` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_total_students1_idx` (`students_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
